// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Kv is an autogenerated mock type for the kv type
type Kv struct {
	mock.Mock
}

type Kv_Expecter struct {
	mock *mock.Mock
}

func (_m *Kv) EXPECT() *Kv_Expecter {
	return &Kv_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *Kv) Get(key string) ([]byte, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Kv_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Kv_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Kv_Expecter) Get(key interface{}) *Kv_Get_Call {
	return &Kv_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *Kv_Get_Call) Run(run func(key string)) *Kv_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Kv_Get_Call) Return(_a0 []byte, _a1 error) *Kv_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Kv_Get_Call) RunAndReturn(run func(string) ([]byte, error)) *Kv_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: key, value
func (_m *Kv) Put(key string, value []byte) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Kv_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type Kv_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key string
//   - value []byte
func (_e *Kv_Expecter) Put(key interface{}, value interface{}) *Kv_Put_Call {
	return &Kv_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *Kv_Put_Call) Run(run func(key string, value []byte)) *Kv_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *Kv_Put_Call) Return(_a0 error) *Kv_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Kv_Put_Call) RunAndReturn(run func(string, []byte) error) *Kv_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewKv creates a new instance of Kv. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKv(t interface {
	mock.TestingT
	Cleanup(func())
}) *Kv {
	mock := &Kv{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
